# Generated by Django 5.2.3 on 2025-11-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('batch_number', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_code_img', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('qr_code_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
